// src/config.ts

// Sample data for your Art Fest Events
export const EVENTS = [
    { id: 'JUON13', name: 'READING ARABIC' },
    { id: 'SEON09', name: 'DEBATE MAL Sen' },
    { id: 'SEON05', name: 'MR ENG Sen' },
    { id: 'JUON02', name: 'SPEECH MAL Jun' },
    { id: 'SEON02', name: 'SPEECH MAL Sen' },
    { id: 'GEON11', name: 'SPEECH URD' },
    { id: 'JUON10', name: 'THINK TALK Jun' },
    { id: 'SJON05', name: 'SONG ARB Sub-Jun' },
    { id: 'SEON13', name: 'INTERVIEW' },
    { id: 'GEON01', name: 'MASHUP Gen' },
    { id: 'GEON08', name: 'ARABIC COMMENTARY' },
    { id: 'GEON09', name: 'TEDX TALK Gen' },
    { id: 'SEON01', name: "QIRA'ATH Sen" },
    { id: 'SEON11', name: 'ENCOUNTER' },
    { id: 'GEON07', name: 'URDU GAZAL' },
    { id: 'SEON10', name: 'THINK TALK Sen' },
    { id: 'SEON18', name: 'WORD FIGHT ARA Sen' },
    { id: 'SJON06', name: 'WORD FIGHT ENG Sub-Jun' },
    { id: 'JUON15', name: 'SONG ARB Jun' },
    { id: 'JUON08', name: 'DEBATE ARB Jun' },
    { id: 'JUON07', name: 'DEBATE ENG Jun' },
    { id: 'SEON17', name: 'WORD FIGHT ENG Sen' },
    { id: 'GEON10', name: 'RJ TALK' },
    { id: 'GEON12', name: 'MR FAQEEH' },
    { id: 'SJON12', name: 'TEDX TALK Sub-Jun' },
    { id: 'SJON04', name: 'SONG MAL Sub-Jun' },
    { id: 'JUON05', name: 'MR ENG Jun' },
    { id: 'SJON10', name: 'AZAN' },
    { id: 'JUON17', name: 'WORD FIGHT ENG Jun' },
    { id: 'GEON02', name: 'SKIT' },
    { id: 'JUON09', name: 'DEBATE MAL Jun' },
    { id: 'FNON02', name: 'CONVERSATION MAL Fnd' },
    { id: 'FNON01', name: 'MASHUP Fnd' },
    { id: 'SEON15', name: 'SONG MALAYALAM' },
    { id: 'JUON11', name: 'REACTING Jun' },
    { id: 'JUON01', name: "QIRA'ATH Jun" },
    { id: 'SEON07', name: 'DEBATE ENG Sen' },
    { id: 'SEON12', name: 'ROLE PLAY Sen' },
    { id: 'JUON16', name: 'WORD FIGHT ARA Jun' },
    { id: 'SEON19', name: 'SPELLING BEE Sen' },
    { id: 'JUON18', name: 'SPELLING BEE Jun' },
    { id: 'SJON02', name: 'SPEECH MAL Sub-Jun' },
    { id: 'SEON06', name: 'MR ARB Sen' },
    { id: 'SEON14', name: 'MY PITCH' },
    { id: 'SEON16', name: 'SONG ARABIC' },
    { id: 'SJON03', name: 'SPEECH ENG Sub-Jun' },
    { id: 'GEON06', name: 'ORU NIMISHAM' },
    { id: 'SJON01', name: "QIRA'ATH Sub-Jun" },
    { id: 'JUON06', name: 'MR ARB Jun' },
    { id: 'GEON04', name: "HIFZ QUR'AN" },
    { id: 'GEON03', name: "MUSHA'ARAH" },
    { id: 'JUON03', name: 'SPEECH ENG Jun' },
    { id: 'JUON04', name: 'SPEECH ARB Jun' },
    { id: 'SEON03', name: 'SPEECH ENG Sen' },
    { id: 'SJON11', name: 'STORY NARRATION Sub-Jun' },
    { id: 'SEON04', name: 'SPEECH ARB Sen' },
    { id: 'JUON14', name: 'SONG MAL Jun' },
    { id: 'SJON07', name: 'SPELLING BEE Sub-Jun' },
    { id: 'GEON05', name: 'REEL MAKING' },
    { id: 'SEON08', name: 'DEBATE ARB Sen' },
    { id: 'JUON12', name: 'ROLE PLAY Jun' },
    { id: 'OFFI01', name: 'OFFICIALS' },
];

// Your 7 College Classes
export const CLASSES = [
    { id: 'C1', name: 'Inshirah' },
    { id: 'C2', name: 'Ishraq' },
    { id: 'C3', name: 'Al Abthal' },
    { id: 'C4', name: 'Uswa' },
    { id: 'C5', name: 'Ithqan' },
    { id: 'C6', name: 'FN A' },
    { id: 'C7', name: 'FN B' },
    { id: 'O1', name: 'STAFF' },
    { id: 'O2', name: 'GUEST' },
];

export const INDIVIDUALS = [
    { id: 'I_224', name: 'RAEES.P' },
    { id: 'I_251', name: 'ZAYAN VP' },
    { id: 'I_261', name: 'IRFAN V' },
    { id: 'I_220', name: 'ABDULHADI K' },
    { id: 'I_183', name: 'SABIQ' },
    { id: 'I_233', name: 'RAZIN AHAMMED' },
    { id: 'I_226', name: 'RAJIH RAYYAN' },
    { id: 'I_258', name: 'ADINAN SALEEM' },
    { id: 'I_135', name: 'HASHIM PP' },
    { id: 'I_245', name: 'ABDHUL KAREEM AV' },
    { id: 'I_168', name: 'JUNAID AK' },
    { id: 'I_133', name: 'DILSHAD' },
    { id: 'I_195', name: 'SHAMIL' },
    { id: 'I_113', name: 'THABSHEER' },
    { id: 'I_202', name: 'MIDLAJ A' },
    { id: 'I_122', name: 'SANAH' },
    { id: 'I_181', name: 'ADIL S' },
    { id: 'I_139', name: 'YASEEN PS' },
    { id: 'I_221', name: 'AMJAD SHAMMAS PV' },
    { id: 'I_112', name: 'AHMAD' },
    { id: 'I_231', name: 'SAJAD.P' },
    { id: 'I_205', name: 'ISHTHIYAQ' },
    { id: 'I_140', name: 'RAHEES' },
    { id: 'I_115', name: 'LATHEEF' },
    { id: 'I_191', name: 'AKBAR SHUHAIB' },
    { id: 'I_149', name: 'FAYIZ' },
    { id: 'I_120', name: 'FARHAN' },
    { id: 'I_104', name: 'SHUHAIB' },
    { id: 'I_208', name: 'MIDLAJ' },
    { id: 'I_114', name: 'SINAN TP' },
    { id: 'I_194', name: 'ADHIL' },
    { id: 'I_255', name: 'FADHI AHAMMED T' },
    { id: 'I_152', name: 'HAMDAN' },
    { id: 'I_193', name: 'NASIH' },
    { id: 'I_160', name: 'FASLURAHMAN EC' },
    { id: 'I_190', name: 'SAFVAN' },
    { id: 'I_137', name: 'FARIS' },
    { id: 'I_145', name: 'FAHEEM' },
    { id: 'I_222', name: 'HIRAZ AZAM' },
    { id: 'I_155', name: 'AJSHAL' },
    { id: 'I_257', name: 'RIZWAN' },
    { id: 'I_121', name: 'SHIMJAS' },
    { id: 'I_256', name: 'SHIHAB' },
    { id: 'I_199', name: 'IRFAN' },
    { id: 'I_103', name: 'SINAN AK' },
    { id: 'I_175', name: 'HARSHAD' },
    { id: 'I_151', name: 'ADIL JAWAD' },
    { id: 'I_234', name: 'RISWAN E K' },
    { id: 'I_105', name: 'MUEENUDHEEN JOUHAR' },
    { id: 'I_262', name: 'SHABIN KT' },
    { id: 'I_153', name: 'SINAN KP' },
    { id: 'I_148', name: 'RAZEEK' },
    { id: 'I_146', name: 'SHANIF MT' },
    { id: 'I_266', name: 'IQBAL' },
    { id: 'I_207', name: 'RASHID' },
    { id: 'I_265', name: 'IHSAN M' },
    { id: 'I_227', name: 'AJWAD K' },
    { id: 'I_235', name: 'SAFEER   C A' },
    { id: 'I_162', name: 'SAYYID ARIF' },
    { id: 'I_225', name: 'SINAN VK' },
    { id: 'I_216', name: 'NASIH SAIFUDHEEN' },
    { id: 'I_206', name: 'SHAMIL PM' },
    { id: 'I_111', name: 'AIMEN' },
    { id: 'I_196', name: 'MINHAJ' },
    { id: 'I_109', name: 'ADHIL SALI' },
    { id: 'I_107', name: 'SUFIYAN' },
    { id: 'I_186', name: 'FAHAD (AL)' },
    { id: 'I_158', name: 'MUHAMMED T (AL)' },
    { id: 'I_267', name: 'THOHA BISHR' },
    { id: 'I_179', name: 'SHAHAD' },
    { id: 'I_185', name: 'BASITH PM (L)' },
    { id: 'I_132', name: 'FAVAS' },
    { id: 'I_157', name: 'SAHAL SALEEM (L)' },
    { id: 'I_166', name: 'SWABEEH' },
    { id: 'I_123', name: 'SHAFIN' },
    { id: 'I_184', name: 'RIDHAN' },
    { id: 'I_176', name: 'ADHIL T' },
    { id: 'I_144', name: 'AL AMEEN' },
    { id: 'I_174', name: 'ABDUL BASITH' },
    { id: 'I_203', name: 'BADRUDHEEN' },
    { id: 'I_217', name: 'AFSWAH V N' },
    { id: 'I_253', name: 'SAYYID RUWAIF' },
    { id: 'I_241', name: 'ANSIL MK' },
    { id: 'I_212', name: 'JUNAID' },
    { id: 'I_170', name: 'BAKKIR' },
    { id: 'I_119', name: 'SHAMIL VT' },
    { id: 'I_236', name: 'SAYYID ABDUL BASITH' },
    { id: 'I_169', name: 'SHAMNAD' },
    { id: 'I_172', name: 'RASHIK' },
    { id: 'I_201', name: 'SHAMEEM EC' },
    { id: 'I_173', name: 'SHANIF PS' },
    { id: 'I_187', name: 'ALTHAF (AL)' },
    { id: 'I_232', name: 'IZAAN ASHRAF' },
    { id: 'I_143', name: 'MUSTHAFA' },
    { id: 'I_100', name: 'AJMAL (L)' },
    { id: 'I_106', name: 'SAHAL AM' },
    { id: 'I_161', name: 'SWALIH KC' },
    { id: 'I_249', name: 'SAHAL VK' },
    { id: 'I_192', name: 'HASHIM P' },
    { id: 'I_260', name: 'SAFIL CV' },
    { id: 'I_102', name: 'SINAN MK (AL)' },
    { id: 'I_108', name: 'ANSAF AP' },
    { id: 'I_264', name: 'FOUZAN' },
    { id: 'I_238', name: 'HADI. PP' },
    { id: 'I_246', name: 'HANAN P' },
    { id: 'I_129', name: 'RAFI (L)' },
    { id: 'I_134', name: 'JOUHAR M' },
    { id: 'I_242', name: 'AHAMMED ABAN' },
    { id: 'I_147', name: 'SHANIL' },
    { id: 'I_214', name: 'NAZIH' },
    { id: 'I_142', name: 'AJMAL' },
    { id: 'I_128', name: 'RABEEH ISMAIL' },
    { id: 'I_218', name: 'ASHMIL P' },
    { id: 'I_237', name: 'SAYYID   ANFAL' },
    { id: 'I_200', name: 'SINAN AK' },
    { id: 'I_178', name: 'SABITH ALI' },
    { id: 'I_156', name: 'SHAMIL PP' },
    { id: 'I_118', name: 'HANOON' },
    { id: 'I_189', name: 'SALMAN' },
    { id: 'I_223', name: 'INSAF MURAD K' },
    { id: 'I_165', name: 'ADHIL MA' },
    { id: 'I_130', name: 'AJSAL (AL)' },
    { id: 'I_209', name: 'SINAN PC' },
    { id: 'I_125', name: 'HISAN' },
    { id: 'I_131', name: 'AHMAD SHAMEEM (AL)' },
    { id: 'I_167', name: 'SWALIH AM' },
    { id: 'I_243', name: 'MISBAH.PC' },
    { id: 'I_254', name: 'MUNAVVAR ALI' },
    { id: 'I_230', name: 'AMAAN S' },
    { id: 'I_117', name: 'MIDLAJ RAHMAN' },
    { id: 'I_204', name: 'SADIQ' },
    { id: 'I_116', name: 'ABDUL RAHEEM' },
    { id: 'I_247', name: 'YASIN SHEREEF' },
    { id: 'I_101', name: 'NABHAN (AL)' },
    { id: 'I_124', name: 'SABOOR' },
    { id: 'I_110', name: 'ZAKVAN' },
    { id: 'I_182', name: 'ANFAS' },
    { id: 'I_180', name: 'SHIFAS' },
    { id: 'I_154', name: 'SHIBILI' },
    { id: 'I_211', name: 'KHAJA' },
    { id: 'I_213', name: 'AIMAN' },
    { id: 'I_229', name: 'NABHAN.M' },
    { id: 'I_198', name: 'AMJAD' },
    { id: 'I_215', name: 'FIZAN.N' },
    { id: 'I_126', name: 'SHAHABAS' },
    { id: 'I_150', name: 'RADHIL' },
    { id: 'I_250', name: 'SHAMSUDHEEN T' },
    { id: 'I_259', name: 'MUHEEN PT' },
    { id: 'I_171', name: 'AHMAD NAJAD' },
    { id: 'I_228', name: 'ASHFIN' },
    { id: 'I_138', name: 'FAHEEM' },
    { id: 'I_248', name: 'OMAR RAFAN' },
    { id: 'I_177', name: 'AJNAS' },
    { id: 'I_141', name: 'SALMANUL FARIS' },
    { id: 'I_188', name: 'ABDUL VAHID' },
    { id: 'I_263', name: 'ANSHIF T' },
    { id: 'I_268', name: 'SINAN P' },
    { id: 'I_210', name: 'MUSTHAEEN' },
    { id: 'I_163', name: 'SHAHIL' },
    { id: 'I_244', name: 'SAFRAS PT' },
    { id: 'I_127', name: 'ADHIL AHMAD' },
    { id: 'I_240', name: 'SHADIN PV' },
    { id: 'I_197', name: 'ADNAN' },
    { id: 'I_252', name: 'NIBRAS AHMMED T' },
    { id: 'I_159', name: 'AHMAD YASEEN (AL)' },
    { id: 'I_239', name: 'BASITH.N' },
    { id: 'I_136', name: 'MUFEED' },
    { id: 'I_219', name: 'LUQMAN' },
    { id: 'I_164', name: 'SWALIH M' },
    { id: 'O_100', name: 'UST AHMAD FAIZY' },
    { id: 'O_101', name: 'UST SALAM FAIZY' },
    { id: 'O_101', name: 'UST ZAKARIYA AHSANI' },
    { id: 'O_102', name: 'UST Saleem Wafy' },
    { id: 'O_103', name: 'UST Ajmal Wafy' },
    { id: 'O_104', name: 'UST Sajid Wafy' },
    { id: 'O_105', name: 'UST Basheer Wafy' },
    { id: 'O_106', name: 'UST Azhar Wafy' },
    { id: 'O_107', name: 'UST Shukoor Wafy' },
    { id: 'O_108', name: 'UST Sayyid Adhil Wafy' },
    { id: 'O_109', name: 'UST Shafi Wafy' },
    { id: 'O_110', name: 'UST Ameen Wafy' },
];