// This file stores all the data for easy selection.

export const EVENTS = [
    { id: 'SJ001', name: 'Football (Junior)' },
    { id: 'JN002', name: 'Football (Senior)' },
    { id: 'SN003', name: 'Football (Super Senior)' },
    { id: 'JN004', name: '100 Meter Race (Junior)' },
    { id: 'JN005', name: '200 Meter Race (Junior)' },
    { id: 'JN006', name: '400 Meter Race (Junior)' },
    { id: 'JN007', name: '800 Meter Race (Junior)' },
    { id: 'JN008', name: '1500 Meter Race (Junior)' },
    { id: 'JN009', name: '3000 Meter Race (Junior)' },
    { id: 'JN010', name: '1000 Meter Walking (Junior)' },
    { id: 'JN011', name: 'Shot Put (Junior)' },
    { id: 'JN012', name: 'Discus Throw (Junior)' },
    { id: 'JN013', name: 'Javelin Throw (Junior)' },
    { id: 'JN014', name: 'Long Jump (Junior)' },
    { id: 'JN015', name: 'High Jump (Junior)' },
    { id: 'JN016', name: 'Triple Jump (Junior)' },
    { id: 'SN017', name: '100 Meter Race (Senior)' },
    { id: 'SN018', name: '200 Meter Race (Senior)' },
    { id: 'SN019', name: '400 Meter Race (Senior)' },
    { id: 'SN020', name: '800 Meter Race (Senior)' },
    { id: 'SN021', name: '1500 Meter Race (Senior)' },
    { id: 'SN022', name: '3000 Meter Race (Senior)' },
    { id: 'SN023', name: '1000 Meter Walking (Senior)' },
    { id: 'SN024', name: 'Shot Put (Senior)' },
    { id: 'SN025', name: 'Discus Throw (Senior)' },
    { id: 'SN026', name: 'Javelin Throw (Senior)' },
    { id: 'SN027', name: 'Long Jump (Senior)' },
    { id: 'SN028', name: 'High Jump (Senior)' },
    { id: 'SN029', name: 'Triple Jump (Senior)' },
    { id: 'SJ030', name: '100 Meter Race (Super Junior)' },
    { id: 'SJ031', name: '200 Meter Race (Super Junior)' },
    { id: 'SJ032', name: 'Shot Put (Super Junior)' },
    { id: 'SJ033', name: 'Long Jump (Super Junior)' },
    { id: 'SJ034', name: '4 X 100 Meter Relay (Super Junior)' },
    { id: 'JN035', name: '4 X 100 Meter Relay (Junior)' },
    { id: 'JN036', name: '4 X 200 Meter Relay (Junior)' },
    { id: 'SN037', name: '4 X 100 Meter Relay (Senior)' },
    { id: 'SN038', name: '4 X 200 Meter Relay (Senior)' },
    { id: 'GN039', name: 'Tug of War (General)' },
];

export const COLLEGES = [
    { id: '1', name: 'KKHM ISLAMIC & ARTS COLLEGE' },
    { id: '2', name: 'RASHEEDIYYA ISLAMIC & ARTS COLLEGE' },
    { id: '4', name: 'MAJMA\'A SHAREE-ATH & ARTS COLLEGE' },
    { id: '11', name: 'PMSA POOKOYA THANGAL ISLAMIC & ARTS COLLEGE' },
    { id: '17', name: 'DARUL ULOOM ISLAMIC & ARTS COLLEGE' },
    { id: '21', name: 'BAFAKHY ISLAMIC& ARTS COLLEGE' },
    { id: '32', name: 'ASSHUHADA ISLAMIC DA\'WA COLLEGE' },
    { id: '33', name: 'DARUSSALAM ISLAMIC & ARTS COLLEGE' },
    { id: '34', name: 'NATTUKAL MAKHAM ISLAMIC & ARTS COLLEGE' },
    { id: '35', name: 'MTM ISLAMIC & ARTS COLLEGE' },
    { id: '47', name: 'MAQDOOMIYYA COLLEGE FOR ISLAMIC STUDIES (MIC)' },
    { id: '51', name: 'DARUL IHSAN ISLAMIC ACADEMY' },
    { id: '54', name: 'UMERALI SHIHAB THANGAL ISLAMIC ACADEMY' },
    { id: '59', name: 'SHAMSUL HUDA ISLAMIC ACADEMY' },
    { id: '76', name: 'MAJLIS UMARIYYA ISLAMIC & ARTS COLLEGE' },
    { id: '77', name: 'WAFY CAMPUS' },
    { id: '85', name: 'SHIHAB THANGAL ISLAMIC & ARTS COLLEGE' },
    { id: '101', name: 'MADARIJUSSUNNA ISLAMIC COLLEGE' },
    { id: '115', name: 'MALIK DEENAR QURAN RESEARCH INSTITUTE - WAFY CAMPUS' },
    { id: '117', name: 'SWAHABA ISLAMIC ACADEMY' },
    { id: '119', name: 'DARUL TARBIYYAH ISLAMIC ACADEMY' },
    { id: '123', name: 'RAHMANIYA ISLAMIC & ARTS COLLEGE' },
    { id: '126', name: 'PANGIL AHMED KUTTY MUSLIYAR WAFY COLLEGE' },
    { id: '127', name: 'HUJJATHUL ISLAM WAFY COLLEGE' },
    { id: '129', name: 'DARUL ATHFAL WAFY ARTS COLLEGE' },
    { id: '131', name: 'VARAKKAL MULLAKOYA THANGAL WAFY COLLEGE' },
    { id: '134', name: 'SHAMSUL ULAMA MEMORIAL RIYALUSSALIHEEN WAFY COLLEGE' },
    { id: '138', name: 'MUNEERUL ISLAM ARABIC (WAFY) COLLEGE, KUNDUMAN, KOLLAM' },
];